{% extends "layouts/docs.swig" %}
{% set active = "jquery-ui" %}

{% block content %}
    <aside class="col col-small-3 col-large-2" id="sidebar-wrapper">
        <ul class="syo-nav syo-nav-list" id="sidebar">
            <li class="syo-nav-header"><i class="icon-flag"></i> Componentes</li>
            
        </ul>
    </aside>

    <div class="col col-small-9 col-large-10">
        
    </div>
{% endblock %}